Update py-quality.yml

diff --git a/.github/workflows/py-quality.yml b/.github/workflows/py-quality.yml
--- a/.github/workflows/py-quality.yml
+++ b/.github/workflows/py-quality.yml
@@ -1,87 +1,39 @@
-name: Python Quality PR Check
+name: python quality check
 
 on:
   pull_request:
     branches:
-      - develop
       - main
+      - develop
 
 jobs:
-  Build-develop:
-    if: github.base_ref == 'develop'
+  Build:
     runs-on: ubuntu-latest
-    env:
-      PYTHONPATH: .
-    defaults:
-      run:
-        working-directory: python
+
     steps:
-      - name: Checkout code
+      - name: checkout source code
         uses: actions/checkout@v4
 
-      - name: Validate PR branch name
+      - name: Validate Branch Constraints
         run: |
-          if [[ ! "${GITHUB_HEAD_REF}" =~ ^(feature|bugfix)/ ]]; then
-            echo "Invalid branch name: ${GITHUB_HEAD_REF}"
+          echo "Source (head): ${GITHUB_HEAD_REF}"
+          echo "Target (base): ${GITHUB_BASE_REF}"
+
+          if [[ "${GITHUB_BASE_REF}" == "main" ]]; then
+            if [[ ! "${GITHUB_HEAD_REF}" =~ ^(release|hotfix)/ ]]; then
+              echo "Invalid: Only release/* or hotfix/* branches can target main."
+              exit 1
+            fi
+
+          elif [[ "${GITHUB_BASE_REF}" == "develop" ]]; then
+            if [[ ! "${GITHUB_HEAD_REF}" =~ ^(feature|bugfix)/ ]]; then
+              echo "Invalid: Only feature/* or bugfix/* branches can target develop."
+              exit 1
+            fi
+
+          else
+            echo "Follow PR rules: target must be main or develop."
             exit 1
           fi
 
-      - name: Set up Python
-        uses: actions/setup-python@v6
-        with:
-          python-version: '3.11'
-
-      - name: Install dependencies
-        run: pip install -r requirements.txt
-
-      - name: Run Lints and Code formatting
-        uses: astral-sh/ruff-action@v3.5.1
-        with:
-          args: check .
-          src: .
-
-      - name: Run Unit Tests and Coverage
-        run: |
-          python -m unittest 
-          coverage run -m unittest
-          coverage report -m
-
-      - name: Compile Code
-        run: python -m compileall .
-
-  Build-Main:
-    if: github.base_ref == 'main'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Validate PR branch name
-        run: |
-          if [[ ! "${GITHUB_HEAD_REF}" =~ ^(release|hotfix)/ ]]; then
-            echo "Invalid branch name: ${GITHUB_HEAD_REF}. "
-            exit 1
-          fi
-
-      - name: Set up Python
-        uses: actions/setup-python@v6
-        with:
-          python-version: '3.11'
-
-      - name: Install dependencies
-        run: pip install -r requirements.txt
-
-      - name: Run Lints and Code formatting
-        uses: astral-sh/ruff-action@v3.5.1
-        with:
-          args: check .
-          src: .
-
-      - name: Run Unit Tests and Coverage
-        run: |
-          python -m unittest 
-          coverage run -m unittest
-          coverage report -m
-
-      - name: Compile Code
-        run: python -m compileall .
+          echo "Valid PR: ${GITHUB_HEAD_REF} → ${GITHUB_BASE_REF}"
